### ISSUE TITLE
To use RP2040-Zero instead of ProMicro...

### ISSUE THREAD

**Issue by azhizhinov** [durken1/pierce#10]
Hello, good fellow.
Can I borrow your attention one more time?
How do you think, is it possible?
Thanks in advance.
[20230908.DURKEN1.PIERCE-RECEVIER.00.pdf](https://github.com/durken1/pierce/files/12559201/20230908.DURKEN1.PIERCE-RECEVIER.00.pdf)

**Comment by azhizhinov** [comment]
Hello.
It can be done in this way.
Need some help here.
![20230915 AZHIZHINOV PIERCE-RECEIVER 01](https://github.com/durken1/pierce/assets/13044908/97a42704-649d-47e0-801b-9dd79538ffbc)
![20230915 AZHIZHINOV PIERCE-RECEIVER 02](https://github.com/durken1/pierce/assets/13044908/2a8ca9f2-5927-4900-80f7-2cd96c5b18e8)
![20230915 AZHIZHINOV PIERCE-RECEIVER 03](https://github.com/durken1/pierce/assets/13044908/565e7ea0-ca53-4fa0-bcb5-d853164cb128)

**Comment by durken1** [comment]
Hello! Sorry for the late reply.
Did you get any further with this? I would assume the voltage regulator is not needed since the rp2040 runs on 3.3 V and the zero already has a regulator.

**Comment by azhizhinov** [comment]
Hello.
Thanks for your answer.
I made the same assumption, but was not sure enough.

**Comment by azhizhinov** [comment]
Hello.
Re-done. :-)
![20231016 AZHIZHINOV PIERCE-RECEIVER-ZERO 00](https://github.com/durken1/pierce/assets/13044908/7e9a1dd2-ebaa-4c85-b23a-8a5055131c75)
![20231016 AZHIZHINOV PIERCE-RECEIVER-ZERO 01](https://github.com/durken1/pierce/assets/13044908/a75f0750-493a-4e8d-8968-ec3c128247d4)
![20231016 AZHIZHINOV PIERCE-RECEIVER-ZERO 02](https://github.com/durken1/pierce/assets/13044908/9a124211-95e0-48ea-9a0d-783538640415)
[20231016.PIERCE-RECEIVER-ZERO.00.zip](https://github.com/durken1/pierce/files/12913877/20231016.PIERCE-RECEIVER-ZERO.00.zip)

**Comment by azhizhinov** [comment]
Can't stop this. :-)
![20231016 AZHIZHINOV PIERCE-RECEIVER-COMBO 00](https://github.com/durken1/pierce/assets/13044908/69d17183-8df1-4bb9-8434-4506b05d000f)
![20231016 AZHIZHINOV PIERCE-RECEIVER-COMBO 01](https://github.com/durken1/pierce/assets/13044908/91f0b879-3223-461b-94dc-a0fc009d4cdd)
[20231016.PIERCE-RECEIVER-COMBO.00.zip](https://github.com/durken1/pierce/files/12914579/20231016.PIERCE-RECEIVER-COMBO.00.zip)

**Comment by weekinro** [comment]
你好，这太棒了，请问有代码吗
