### ISSUE TITLE
Receiver box case

### ISSUE THREAD

**Issue by tokyo2006** [durken1/pierce#11]
This is a cool mechanical keyboard. I followed your guide and assembled it. 
![44289846A494BC948F961EF20465FBC8](https://github.com/durken1/pierce/assets/926759/73ce4ad1-a434-4873-93a1-11682c1fa5bc)
But I didn't find a receiver box case, so I created it, and I attached this here
[receiver_box_case.zip](https://github.com/durken1/pierce/files/14354507/receiver_box_case.zip)

**Comment by durken1** [comment]
Thank you!
Can I add the STLs to the repo? If you want you can add them yourself and do a PR or I can just add them and give you credit.

**Comment by tokyo2006** [comment]
yes, you can!, please feel free to add these STLs to the repo. I attached the file, because I think you can easily add it , and I don't need to create PR. :)
