### ISSUE TITLE
Hello, good fellow.

### ISSUE THREAD

**Issue by azhizhinov** [durken1/pierce#2]
Hello, good fellow.
Very interesting project.
Are these samples are completely functional?
Don't you mind if I've try to solder fully wireless one with dongle?
Thanks for your efforts.

**Comment by durken1** [comment]
Hello,
You're very welcome to build it!
Everything is fully functional (I'm using this version as my daily driver). 
I have a pending PR to the qmk main repo, but until it's approved you can get it here: https://github.com/durken1/qmk_firmware/tree/pierce/keyboards/pierce

**Comment by azhizhinov** [comment]
Hello.
It seems, that you uses different case model for pierce 2.0.
Old cases looks too high.
Do you have some plans to release new case models?
Thanks in advance.

**Comment by durken1** [comment]
Yes, that's true, the old case won't fit. I have made some simple bottom plates that I use. I'll add the STLs when I get the chance.

**Comment by azhizhinov** [comment]
Hello.
Just in case. :-)
[pierce-top-bottom-plates.zip](https://github.com/durken1/pierce/files/8727104/pierce-top-bottom-plates.zip)

**Comment by durken1** [comment]
Nice, if you decide to try them let me know how they work and I can add them to the repo.
I added the plates that I use. The screwless uses friction fit to attach the pcbs for a plateless build. The margins at the mounting points are quite small, so dependig on the printer it migh work better or worse.

**Comment by azhizhinov** [comment]
Hello.
Thanks a lot.
For how long CR2032 will provide enough power for a half with daily usage?
At what distance from the halves does the receiver still provide stable communication?

**Comment by durken1** [comment]
It's a bit difficult to say. They should last for almost 1000 hours of active typing and with current firmware they go to deep sleep after 0.5 seconds. So it kinda depends on how much you type during daily usage. But to give an estimate, I used the prototype for about 9 months before having to change the battery.

I have tried them from about 3 meters away and through a door without issue. I can do some more testing to find out how far before they fail if you're interested.

**Comment by azhizhinov** [comment]
Cool. This information is enough for me.
Good results.

**Comment by azhizhinov** [comment]
Hello.
Please, advice, how can I mirror wireless_bottom_screwless.3mf?
It's for left the half, right?
How the same model can be printed for the left half?
A 3D printer can mange such situation?
Thanks in advance.

**Comment by durken1** [comment]
Yes, it's the left half. It can easily be mirrored in the slicing software before printing.

**Comment by azhizhinov** [comment]
Is it not planned to use the top plate for Cherries, as for Alps?
Are the Cherries stable enough without the top plate?

**Comment by durken1** [comment]
I will make a top plate for MX switches as well. At the moment I don't have much time though, but it's coming :). If the switches are 5 pin you don't have to have a top plate. If they are 3 pin you need a plate. You can see the difference here: https://m.media-amazon.com/images/I/61kURKmWOvL._AC_SL400_.jpg

**Comment by azhizhinov** [comment]
Yep, time is always passing by.
Ok, I see, mine are 3-pin.
I think alps_plate.3mf can be used as well.
The Alps are for 15x14 mm cuts, the Cherries are for 14x14 cuts, centers of switches are the same, I think.
But borders of the bottom plate should be higher then, to hide the PCB itself and the top plate.

**Comment by azhizhinov** [comment]
Hello.
Do you have the case parts in .STL format?
It's more comfortable for editing with some free tools like FreeCAD.
Will be great to adopt this kind of bottom plate to Pierce, how do you think?
https://github.com/mattdibi/redox-keyboard/blob/master/redox-w/rev2.0WHS/case/BackplateL.stl
https://github.com/mattdibi/redox-keyboard/blob/master/redox-w/rev2.0WHS/case/OpenBackplateL.stl

**Comment by durken1** [comment]
Hi!

I can export the case parts to STL when I get home from work today.
Regarding the other type of bottom plates, that's not really something I would find useful, but if you want to make them I'm happy to include them in the repo.

**Comment by azhizhinov** [comment]
Hello.
Yes, that would be great if you'll publish plates in a format, editable with free tools.
I'm not familiar with 3D tools at this moment, but I'll try to mess with. ;-)
Have a nice day.

**Comment by azhizhinov** [comment]
Hello.
There is some automation for cases.
May be you'll find this interesting.
https://github.com/Lenbok/scad-keyboard-cases

**Comment by durken1** [comment]
That looks very interesting, will check it out!
Also I apologize for not being more active here at the moment, don't have much spare time right now.

**Comment by azhizhinov** [comment]
Hello.
It seems, I've successfully flashed pierce_dongle.bin to the dongle. :-)
Open On-Chip Debugger 0.11.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
WARNING: interface/stlink-v2.cfg is deprecated, please switch to interface/stlink.cfg
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : clock speed 1000 kHz
Info : STLINK V2J29S7 (API v2) VID:PID 0483:3748
Info : Target voltage: 3.324324
Info : nrf51.cpu: hardware has 4 breakpoints, 2 watchpoints
Info : starting gdb server for nrf51.cpu on 3333
Info : Listening on port 3333 for gdb connections
Info : accepting 'telnet' connection on tcp/4444
target halted due to debug-request, current mode: Handler HardFault
xPSR: 0xc1000003 pc: 0xfffffffe msp: 0xffffffd8
Info : nRF51822-QFAA(build code: H0) 256kB Flash, 16kB RAM
Info : Mass erase completed.
Info : A reset or power cycle is required if the flash was protected before.
target halted due to debug-request, current mode: Thread 
xPSR: 0xc1000000 pc: 0xfffffffe msp: 0xfffffffc
** Programming Started **
Warn : Adding extra erase range, 0x00003f04 .. 0x00003fff
** Programming Finished **

**Comment by azhizhinov** [comment]
I've made the switch plate for MX-type switches, but I don't know how to make holes. :-)
[20220628.DURKEN1.PIERCE.00.zip](https://github.com/durken1/pierce/files/9004524/20220628.DURKEN1.PIERCE.00.zip)

**Comment by azhizhinov** [comment]
Hello.
An idea for the case, maybe that style already used in some projects, I don't know.
To fasten the switch plate with the bottom plate through the PCB.
![20220629 DURKEN1 PIERCE 00](https://user-images.githubusercontent.com/13044908/176406717-d5872655-43f7-4030-b230-4eab44c82105.jpg)

**Comment by durken1** [comment]
Hello. 
You can find the position of the holes on the pcb using kicad (pcbnew).
Regarding the mounting I guess it should work, but personally i prefer solutions that you can disassemble more easily. But let me know if you try it out and how it works!

And nice to see you flashed the dongle successfully :) please keep me updated on your build.

**Comment by azhizhinov** [comment]
Hello.
Yep, I get to this point with the same conclusion. It's better to have possibility to disassemble a keyboard.
I've studied a lot of videos and now have better understanding of  KiCAD -> Blender process.
Sure will update, next step is to solder one of the halves and test with dongle.

**Comment by azhizhinov** [comment]
Hello.
That was my first challenge with Blender.
So, here the result.
Could you, please check?
Do you have possibility to print these plates?
[20220702.DURKEN1.PIERCE.00.zip](https://github.com/durken1/pierce/files/9033579/20220702.DURKEN1.PIERCE.00.zip)

**Comment by azhizhinov** [comment]
Hello.
I'm finished.
Now time for keymap/layers. :-)
Have you any plans for VIA/VIAL support?
Thanks in advance.
![IMG_20220820_230430](https://user-images.githubusercontent.com/13044908/185784742-91ed0044-762d-4955-bf63-14c8bb14d074.jpg)

**Comment by durken1** [comment]
Looks good! How do you like it?

No plans for via/vial support at the moment. Feel free to add it and make a PR though :)

**Comment by durken1** [comment]
Are the plates working as intended? If so, would you mind adding them to the plates-folder with a PR? :)

**Comment by azhizhinov** [comment]
> Are the plates working as intended? If so, would you mind adding them to the plates-folder with a PR? :)

Hello.
I've made the PR for plates.
And for via support also.
Have a nice day.

**Comment by azhizhinov** [comment]
Hello.
Pierce now has support from VIA.
https://github.com/the-via/keyboards/pull/1747
Stay safe.

**Comment by durken1** [comment]
Hello,
Nice! Thank you for your contribution!
