### ISSUE TITLE
Flesh out build guide

### ISSUE THREAD

**Issue by chewiedies** [durken1/pierce#6]
I am having a lot of trouble flashing the wireless modules. The instructions in the build guide are quite sparse and seem to make a lot of assumptions. Can you write up a more robust build guide with regards to firmware flashing and wireless module flashing?

**Comment by azhizhinov** [comment]
Hello.
Sorry for shameless intervene.
I've flashed at least 12 modules.
It's easy with ST-Link and openocd.
Just need a Linux installation with openocd.
You have to connect a wireless module with a ST-Link programmer.
Create nameitasyouwant.cfg with the following:
```
#nRF51822 Target
source [find interface/stlink.cfg]
transport select hla_swd
set WORKAREASIZE 0x4000
source [find target/nrf51.cfg]
```

Start the openocd process with `openocd -f nameitasyouwant.cfg`.

Connect to the openocd server with `telnet localhost 4444` and issue these commands:
```
halt
nrf51 mass_erase
program <full path to firmware>.bin
reset
```
The firmware for [dongle](https://github.com/durken1/pierce/blob/master/wireless_modules_firmware/dongle/bin/pierce_dongle.bin).
The firmware for the [left controller](https://github.com/durken1/pierce/blob/master/wireless_modules_firmware/wireless/bin/left/pierce_wireless_left.bin).
The firmware fore the [right controller](https://github.com/durken1/pierce/blob/master/wireless_modules_firmware/wireless/bin/right/pierce_wireless_right.bin).
Thats it.

**Comment by azhizhinov** [comment]
Basically it's the same process as described [here](https://github.com/mattdibi/redox-keyboard/tree/master/redox-w#firmware) for Redox.

**Comment by chewiedies** [comment]
I actually got it working after I submitted this issue. I used this guide to get it all working: https://docs.beekeeb.com/other-guides/how-to-flash-a-firmware-with-openocd. After I had OpenOCD and MSYS2 installed it all started to make more sense.  I also had a different programmer which required a different interface config. Once I figured out my issues and how my setup differed slightly from the build guide it all went smoothly.

**Comment by azhizhinov** [comment]
Hello. @chewiedies 
Nice [build](https://www.reddit.com/r/ErgoMechKeyboards/comments/103fknc/my_first_5col_pierce_wireless_running_qmk/).
Will you share the case? :-)

**Comment by chewiedies** [comment]
> Hello. @chewiedies Nice [build](https://www.reddit.com/r/ErgoMechKeyboards/comments/103fknc/my_first_5col_pierce_wireless_running_qmk/). Will you share the case? :-)

@azhizhinov I am still revising the design after the first print. I'm nearly done and will upload it here once I finish. https://www.printables.com/social/360738-chewiedies/models

**Comment by durken1** [comment]
Glad you got it working! And really nice build, hope you like it :)
