### ISSUE TITLE
Choc V1 compatibility

### ISSUE THREAD

**Issue by ruehri** [durken1/pierce#8]
Hey I saw the layout should be compatible with choc V1 sockets. Normally you would solder the socket on the bottom of the key, but in the layout here all pin holes seem to be on the top. Do I understand it correctly that choc V1 sockets and switches would be soldered/attached upside down?

**Comment by durken1** [comment]
Hi,

It doesn't support any sockets, only switches soldered directly to the PCB

**Comment by ruehri** [comment]
Ah got it, thanks a lot for the clarification!
